FROM python:3.7.8-slim

WORKDIR /usr/src/app

COPY requirements.api.txt .

RUN pip install --no-cache-dir -r requirements.api.txt

COPY api ./api
COPY domain ./domain
COPY api.py .

CMD ["python", "api.py"]