apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrobus-pv
spec:
  storageClassName: metrobus-storage
  capacity:
    storage: 7Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"