apiVersion: v1
kind: ReplicationController
metadata:
  name: cron
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: cron
    spec:
      containers:
        - name: cron
          image: krabbit1993/metrobus_cron:1.0.2
          imagePullPolicy: IfNotPresent
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-database-access
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-database-access
                  key: password
            - name: DB_DATABASE
              value: metrobus
            - name: DB_HOST
              value: database-svc
            - name: DB_PORT
              value: '3306'